### PR TITLE
typo unline -> unlike

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by cordoval** [comment]
@schacon kindly please merge this

**Comment by cordoval** [comment]
ping @matthewmccullough @schacon @progit

**Comment by matthewmccullough** [comment]
Nice detailed catch @cordoval!

**Comment by cordoval** [comment]
@matthewmccullough  like a beast, learnt it from the top guys, from you! :baby: :+1:

**Comment by matthewmccullough** [comment]
:blush:

**Pull request merged**
